name: template-spec-static-web-app
on:
  workflow_dispatch:
  push:
    branches:
      - mastercard

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: templateSpecs
  AZURE_REGION: westeurope
  TEMPLATE_SPEC_NAME: static-web-app
  TEMPLATE_SPEC_FILE_PATH: staticWebAppDeployment.bicep
  TEMPLATE_METADATA_FILE_PATH: metadata.json

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file ${{ env.TEMPLATE_SPEC_FILE_PATH }}

  publish:
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Get module version number
      run: |
        majorMinorVersionNumber=$(jq '(.version.major | tostring) + "." + (.version.minor | tostring)' ${{ env.TEMPLATE_METADATA_FILE_PATH }} -r )
        versionNumber="$majorMinorVersionNumber.${{ github.run_number }}"
        echo "TEMPLATE_VERSION=$versionNumber" >> $GITHUB_ENV
    - uses: azure/cli@v1
      name: Publish template spec
      with:
        inlineScript: |
          az ts create \
            --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
            --name ${{ env.TEMPLATE_SPEC_NAME }} \
            --version ${{ env.TEMPLATE_VERSION }} \
            --template-file ${{ env.TEMPLATE_SPEC_FILE_PATH }} \
            --location ${{ env.AZURE_REGION }} \
            --yes